### ISSUE TITLE
[A/BC] Deleting an exercise then hitting the 'back' button causes application to crash.  Exercise is still present when application is re-opened.

### ISSUE THREAD

**Issue by ThorOfAsgaard** [ThorOfAsgaard/StrengthCalc_Issue_tracker#1]
Stack Trace from Play Store:

ava.lang.IllegalArgumentException: Must specify a valid data set.
at com.google.android.gms.common.internal.zzx.zzb(Unknown Source)
at com.google.android.gms.fitness.request.SessionInsertRequest$Builder.addDataSet(Unknown Source)
at com.asgaardianworkshop.StrengthCalcUltimate.FitRecorder.insertSession(FitRecorder.java:79)
at com.asgaardianworkshop.StrengthCalcUltimate.routineDay_fragment.onDetach(routineDay_fragment.java:881)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1202)
at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1345)
at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:902)
at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1666)
at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:586)
at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:169)
at android.app.Activity.onKeyUp(Activity.java:2669)
at android.view.KeyEvent.dispatch(KeyEvent.java:3214)
at android.app.Activity.dispatchKeyEvent(Activity.java:2937)
at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:224)
at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2609)
at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4884)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4839)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4322)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4375)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4341)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4467)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4349)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4524)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4322)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4375)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4341)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4349)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4322)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4375)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4341)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4500)
at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4714)
at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2784)
at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2376)
at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2367)
at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2761)
at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:143)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:6872)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by ThorOfAsgaard** [comment]
GoogleFit is working appropriately, but dataset is null since user was just editing a routine.  Added != null assertions, should be fixed in v1.91 (published on 3/05/2016) - Fixed on https://github.com/ThorOfAsgaard/strengthcalc-beta/pull/41

**Comment by ThorOfAsgaard** [comment]
Awaiting feedback
