### ISSUE TITLE
[A/C]

### ISSUE THREAD

**Issue by ahluwaliarahul** [ThorOfAsgaard/StrengthCalc_Issue_tracker#2]
App crashes on startup. Phone - Oneplus one, Cyanogen OS 11.0-XNPH05Q, Android 4.4.4

**Comment by ThorOfAsgaard** [comment]
Stack Trace:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.asgaardianworkshop.StrengthCalcUltimate/com.asgaardianworkshop.StrengthCalcUltimate.FullscreenActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
    at android.app.ActivityThread.access$800(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5146)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at com.asgaardianworkshop.StrengthCalcUltimate.FullscreenActivity.onCreate(FullscreenActivity.java:151)
    at android.app.Activity.performCreate(Activity.java:5231)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)

**Comment by ThorOfAsgaard** [comment]
Fix available on version 1.93 on the alpha channel, will push to prod on 3/12/2016
